// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9RDXgw6zBKJoGUPCQshJCbMKOhdUkzbk',
    appId: '1:273886623532:web:c08a713c89721878a4de89',
    messagingSenderId: '273886623532',
    projectId: 'cs326n-busproject',
    authDomain: 'cs326n-busproject.firebaseapp.com',
    storageBucket: 'cs326n-busproject.appspot.com',
    measurementId: 'G-5T7GRKDHE1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuPa0YAVRLaszAV6CQVkCgfnP76Td-Fes',
    appId: '1:273886623532:android:6e85e6b971f5e828a4de89',
    messagingSenderId: '273886623532',
    projectId: 'cs326n-busproject',
    storageBucket: 'cs326n-busproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCkNq2lheCpx2p0IujU3i1iIv15Y8fDRw',
    appId: '1:273886623532:ios:00a8d25bfc255abaa4de89',
    messagingSenderId: '273886623532',
    projectId: 'cs326n-busproject',
    storageBucket: 'cs326n-busproject.appspot.com',
    iosBundleId: 'com.example.msaProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCkNq2lheCpx2p0IujU3i1iIv15Y8fDRw',
    appId: '1:273886623532:ios:962c65f02dd18feba4de89',
    messagingSenderId: '273886623532',
    projectId: 'cs326n-busproject',
    storageBucket: 'cs326n-busproject.appspot.com',
    iosBundleId: 'com.example.msaProject.RunnerTests',
  );
}
